#!/usr/bin/python3

# function to calculate Celsius from Fahrenheit input
def fahrenheitToCelsius(fahrenheit):
	celsius = (fahrenheit - 32.0)*(5.0/9.0)
	return round(celsius, 1)

# function to calculate Fahrenheit from Celsius input
def celsiusToFahrenheit(celsius):
	fahrenheit = (9.0/5.0)*celsius + 32.0
	return round(fahrenheit, 1)

print("Welcome to the CS 3030 Temperature Conversion Program")

# variable to hold while loop
value = 0

# while loop stays active until user inputs '3'
while value != 3:
	print("Main Menu\n\n1:Fahrenheit to Celsius\n2:Celsius to Fahrenheit\n3:Exit program\n")
	selection = input("Please enter 1, 2 or 3:")

	if selection == "1":
		try:
			# cast input as a float to ensure valid entry
			fahrenheit = float(input("Please enter degrees Fahrenheit:"))
			conversion = '{0} degrees Fahrenheit equals {1} degrees Celsius'.format(fahrenheit, fahrenheitToCelsius(fahrenheit))
			print(conversion)
		except:
			print("Invalid entry")

	if selection == "2":
		try:
			# cast input as a float to ensure valid entry
			celsius = float(input("Please enter degrees Celsius:"))
			conversion = '{0} degrees Celsius equals {1} degrees Fahrenheit'.format(celsius, celsiusToFahrenheit(celsius))
			print(conversion)
		except:
			print("Invalid entry")

	if selection == "3":
		# change variable to break out of while loop and exit program
		value = 3
exit(0)
